import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import Quote from '../components/Quote';
import { displayRdm } from '../util/utils';
import { useEffect, useState } from 'react';
import ThemeToggle from '../components/ThemeToggle';

export default function Home({
  books,
  rdmQuote,
  rdmHighlight,
}: InferGetStaticPropsType<typeof getStaticProps>) {
  const [rQuote, setRQuote] = useState(rdmQuote);
  const [rHighlight, setRHighlight] = useState(rdmHighlight);

  useEffect(() => {
    // get init rdm
    updateRdm();
  }, []);

  // FIXME: refactor
  // press Space to update Quote
  useEffect(() => {
    const onSpace = (ev: KeyboardEvent) => {
      if (ev.key === ' ') {
        updateRdm();
      }
    };
    window.addEventListener('keyup', onSpace);
    return () => {
      window.removeEventListener('keyup', onSpace);
    };
  }, []);

  // update state: rdmHighlight
  const updateRdm = () => {
    setRQuote(displayRdm(books).rdmQuote);
    setRHighlight(displayRdm(books).rdmHighlight);
  };

  // keydown
  const keySpaceDown = (event: any) => {
    if (event.key === 'f') {
      console.log('F');
    }
  };

  return (
    <div className={styles.container} onKeyDown={keySpaceDown}>
      <Head>
        <title>Quote</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <div className="absolute top-10 right-10">{renderThemeChnager()}</div> */}

        <ThemeToggle />
        <Quote rdmHighlight={rHighlight} rdmQuote={rQuote} />

        <button
          className="absolute right-10 bottom-10 text-6xl transform transition-all duration-300 hover:scale-95 active:rotate-270"
          onClick={updateRdm}
        >
          🎲
        </button>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  // get data
  const files = fs.readdirSync(path.join('data/books'));

  // get file names without extension
  const books = files.map((fileName) => {
    // create slug
    const slug = fileName.replace('.md', '');

    // get frontmatter
    const markdownWithMeta = fs.readFileSync(
      path.join('data/books', fileName),
      'utf-8'
    );

    // get md
    const { data: frontmatter, content } = matter(markdownWithMeta);

    return {
      slug,
      frontmatter,
      content,
    };
  });

  return {
    props: {
      books,
      rdmQuote: displayRdm(books).rdmQuote,
      rdmHighlight: displayRdm(books).rdmHighlight,
    },
  };
}
